MYSTERIES = [
    {
        "title": "La Gran Pirámide de Giza",
        "img_prompt": "great pyramid of giza ancient egypt desert night sky stars dramatic cinematic lighting mysterious dark atmosphere 8k detailed",
        "script": "La Gran Pirámide de Giza lleva más de cuatro mil quinientos años en pie en el desierto egipcio. Construida con más de dos millones de bloques de piedra, algunos de más de ochenta toneladas, los ingenieros modernos aún no comprenden completamente cómo fue posible. Sus cuatro caras están alineadas con los puntos cardinales con un margen de error de apenas tres centésimas de grado. En el interior, escáneres de muones revelaron en 2017 una cavidad oculta de treinta metros nunca explorada. La temperatura interior permanece constante a veinte grados sin importar el clima exterior. ¿Cómo transportaron esos bloques gigantescos sin maquinaria moderna? ¿Qué hay dentro de esa cavidad oculta? La Gran Pirámide guarda secretos que cuatro milenios de estudio no han podido revelar."
    },
    {
        "title": "La Atlántida: El Continente Perdido",
        "img_prompt": "lost city of atlantis underwater ancient ruins submerged buildings dramatic cinematic lighting mysterious ocean depths 8k detailed",
        "script": "Hace dos mil cuatrocientos años, el filósofo Platón describió una civilización avanzada que desapareció bajo el océano en un solo día y una sola noche. La llamó Atlántida, y dijo que era más grande que Libia y Asia juntas. ¿Era solo una alegoría filosófica o el recuerdo de una catástrofe real? Arqueólogos han buscado sus ruinas en el Mediterráneo, las Azores, las costas de España, e incluso bajo el océano Atlántico. Estudios geológicos muestran que un tsunami devastó las costas atlánticas hace unos cuatro mil años. Algunos investigadores creen haber localizado estructuras geométricas bajo las marismas de Doñana, en España. Si Atlántida existió, su tecnología y conocimiento se perdieron para siempre. El misterio de la civilización hundida sigue fascinando al mundo entero."
    },
    {
        "title": "Stonehenge: El Templo del Silencio",
        "img_prompt": "stonehenge ancient stone circle night full moon dramatic fog mysterious atmosphere cinematic dark fantasy 8k detailed",
        "script": "En medio de la llanura de Salisbury, en Inglaterra, se alzan piedras de hasta cincuenta toneladas colocadas con una precisión asombrosa hace más de cinco mil años. Stonehenge no tiene escritura, no tiene documentos. Nadie sabe con certeza quién lo construyó ni por qué. Las piedras más pequeñas, llamadas bluestones, provienen de Gales, a casi trescientos kilómetros de distancia. ¿Cómo las transportaron sin ruedas ni animales de carga? El conjunto está perfectamente alineado con el amanecer del solsticio de verano. Estudios recientes descubrieron que el sitio fue habitado durante siglos antes de que se colocara la primera piedra. ¿Era un templo de curación, un observatorio astronómico, un lugar para rendir culto a los muertos? Cinco mil años después, Stonehenge sigue sin entregar sus secretos."
    },
    {
        "title": "Las Líneas de Nazca",
        "img_prompt": "nazca lines peru aerial view giant geoglyphs desert mysterious ancient symbols dramatic cinematic bird view 8k detailed",
        "script": "En el desierto peruano, grabadas en la tierra hace más de dos mil años, existen figuras gigantescas que solo pueden verse desde el aire. Un colibrí de noventa y tres metros, una araña de cuarenta y seis, un mono, un cóndor, y cientos de líneas perfectamente rectas que atraviesan cerros como si ignoraran el terreno. La cultura Nazca no tenía aviones ni globos. ¿Cómo trazaron estas figuras con tal precisión sin poder verlas desde arriba? Algunas líneas apuntan exactamente hacia el solsticio. Otras parecen pistas de aterrizaje vistas desde arriba. María Reiche dedicó su vida a estudiarlas, convencida de que eran un calendario astronómico. Pero nadie ha encontrado la respuesta definitiva. Las líneas de Nazca llevan dos mil años esperando que alguien descifre su mensaje."
    },
    {
        "title": "Los Moáis de la Isla de Pascua",
        "img_prompt": "easter island moai stone statues dramatic sunset stormy sky mysterious ancient civilization cinematic 8k detailed",
        "script": "En el punto más remoto del océano Pacífico, una pequeña isla alberga casi mil estatuas de piedra colosales. Los moáis de la Isla de Pascua pesan en promedio catorce toneladas y los más grandes superan las ochenta. Fueron tallados y transportados kilómetros por los rapanui, sin animales de carga ni ruedas. Cuando los primeros europeos llegaron en 1722, preguntaron a los isleños cómo los habían movido. La respuesta fue siempre la misma: las estatuas caminaron solas. Experimentos modernos demostraron que balanceándolas con cuerdas es posible moverlas erectas, como si caminaran. Pero los más grandes desafían cualquier explicación. Debajo de cada moái hay un cuerpo enterrado hasta las caderas, invisible desde la superficie. ¿Qué fuerza impulsó a una pequeña civilización a crear semejantes monumentos?"
    },
    {
        "title": "Göbekli Tepe: El Templo que Reescribió la Historia",
        "img_prompt": "gobekli tepe ancient stone temple pillars carved animals prehistoric ruins dramatic cinematic mysterious night 8k detailed",
        "script": "En 1994, un pastor kurdo encontró en Turquía unas piedras extrañas. Resultaron ser las ruinas del templo más antiguo del mundo: Göbekli Tepe, construido hace doce mil años. Este descubrimiento trastocó todo lo que creíamos saber sobre la prehistoria. Según los libros de historia, los humanos de esa época eran cazadores nómadas, incapaces de construir estructuras monumentales. Sin embargo, Göbekli Tepe tiene columnas de seis metros con relieves de animales perfectamente esculpidos. No había agricultura, no había ciudades, no había escritura. ¿Cómo organizaron cientos de personas durante generaciones para construir esto? Lo más desconcertante: fue enterrado deliberadamente hace unos diez mil años, como si alguien quisiera ocultarlo. Solo se ha excavado el cinco por ciento del yacimiento. Lo que queda bajo tierra podría cambiar la historia de la humanidad."
    },
    {
        "title": "El Mecanismo de Anticitera",
        "img_prompt": "antikythera mechanism ancient greek bronze gears mysterious device dramatic cinematic close up dark background 8k detailed",
        "script": "En 1901, buzos que recuperaban tesoros de un naufragio romano encontraron en Anticitera, Grecia, un trozo de bronce corroído. Décadas después, los científicos descubrieron que era el objeto más extraordinario del mundo antiguo: un ordenador astronómico de hace dos mil cien años. El mecanismo de Anticitera predecía eclipses, calculaba el movimiento de los planetas y seguía el calendario de los Juegos Olímpicos mediante treinta y siete engranajes entrelazados con una precisión micrométrica. Nadie creía que la antigua Grecia tuviera semejante tecnología. Lo más desconcertante es que no existe ningún otro artefacto similar de esa época ni de los siguientes mil años. ¿Quién lo construyó? ¿Existió una tradición de ingeniería mecánica que se perdió completamente? El mecanismo de Anticitera sigue siendo el objeto más misterioso de la antigüedad."
    },
    {
        "title": "La Esfinge de Giza y el Misterio del Agua",
        "img_prompt": "sphinx of giza ancient egypt dramatic stormy sky lightning mysterious erosion water marks cinematic 8k detailed",
        "script": "La Gran Esfinge de Giza es la estatua monolítica más grande del mundo. La historia oficial dice que fue construida por el faraón Quéfren hace cuatro mil quinientos años. Pero el geólogo Robert Schoch encontró algo perturbador en los años noventa: las marcas de erosión en la Esfinge no son del viento ni la arena, sino del agua. Esas marcas de erosión por lluvia intensa requieren un clima muy diferente al actual. El último período húmedo en Egipto terminó hace más de siete mil años. ¿Significa esto que la Esfinge es miles de años más antigua de lo que pensamos? Si es así, fue construida por una civilización que aún no conocemos. La comunidad arqueológica rechazó la teoría, pero nunca la ha refutado convincentemente. El agua no miente, y la Esfinge guarda ese secreto en su piedra."
    },
    {
        "title": "Teotihuacán: La Ciudad de los Dioses",
        "img_prompt": "teotihuacan pyramid of the sun ancient mexico aerial view dramatic sunset mysterious ancient city cinematic 8k detailed",
        "script": "A cincuenta kilómetros de Ciudad de México se alza una ciudad que en su apogeo tenía más de doscientos mil habitantes, la sexta más grande del mundo antiguo. Los aztecas la llamaron Teotihuacán, la ciudad donde los hombres se convierten en dioses, pero cuando llegaron allí en el siglo doce, la ciudad ya llevaba siglos abandonada. No saben quién la construyó. No dejaron escritura descifrable, no sabemos cómo se llamaban, no conocemos su idioma. Sus tres pirámides están alineadas con la constelación de Orión. Bajo la Pirámide de la Serpiente Emplumada existe un túnel lleno de mercurio líquido que nadie ha explorado completamente. En las paredes se encontraron esferas de pirita que reflejan el cielo como espejos. ¿Quiénes fueron los teotihuacanos? La ciudad más misteriosa del continente americano sigue sin dueño conocido."
    },
    {
        "title": "Los Mapas de Piri Reis",
        "img_prompt": "ancient map parchment treasure map mysterious antique ottoman dramatic cinematic dark background cartography 8k detailed",
        "script": "En 1929, en el palacio de Topkapi de Estambul, se encontró un mapa dibujado en 1513 por el almirante otomano Piri Reis. El mapa mostraba las costas de América del Sur con una precisión asombrosa para la época. Pero lo más perturbador era otra cosa: el mapa también representaba la Antártida, cuyas costas no fueron descubiertas oficialmente hasta 1818, tres siglos después. Y no solo eso: el mapa muestra la Antártida sin hielo, tal como estaba hace más de seis mil años, antes de que los glaciares la cubrieran. Piri Reis anotó en el margen que copió su mapa de fuentes mucho más antiguas. ¿Existió una civilización capaz de navegar y cartografiar el mundo entero miles de años antes de lo que creemos? Los mapas de Piri Reis sugieren que sí."
    },
    {
        "title": "El Arca de la Alianza",
        "img_prompt": "ark of the covenant ancient golden box glowing divine light mysterious dramatic desert temple cinematic 8k detailed",
        "script": "Según el Antiguo Testamento, el Arca de la Alianza era un cofre de madera cubierto de oro que contenía las Tablas de la Ley entregadas por Dios a Moisés. Pero el Arca no era solo una reliquia religiosa: los textos bíblicos la describen como un arma capaz de emitir rayos que mataban a quienes la tocaran sin autorización. En la batalla de Jericó, el sonido de trompetas y la presencia del Arca derrumbaron las murallas. Desapareció de Jerusalén hace dos mil seiscientos años y nadie ha vuelto a verla. La Iglesia Etíope de Aksum afirma tenerla custodiada pero no permite ninguna inspección. Arqueólogos israelíes creen que está enterrada bajo el Monte del Templo en Jerusalén, en un túnel sellado. Si el Arca existe, podría ser el artefacto religioso más importante de la historia."
    },
    {
        "title": "Machu Picchu: La Ciudad en las Nubes",
        "img_prompt": "machu picchu inca ancient city clouds mountains dramatic sunrise mysterious cinematic fog 8k detailed",
        "script": "En 1911, el explorador Hiram Bingham descubrió entre las nubes de los Andes peruanos una ciudad inca perfectamente conservada que el mundo había olvidado durante siglos. Machu Picchu fue construida a dos mil cuatrocientos metros de altitud, en un terreno que parece imposible para la construcción. Sus piedras encajan tan perfectamente que ni un papel puede introducirse entre ellas, sin cemento ni argamasa. Fue abandonada solo ochenta años después de su construcción, probablemente por una epidemia de viruela traída por los europeos. Pero los arqueólogos tienen más preguntas que respuestas. ¿Por qué construirla en un lugar tan inaccesible? ¿Qué propósito tenían los misteriosos espejos de piedra que reflejan el amanecer? Más de la mitad de los edificios permanece bajo tierra sin excavar. Machu Picchu sigue revelando secretos inca que esperan ser descubiertos."
    },
    {
        "title": "Los Monolitos de Carnac",
        "img_prompt": "carnac standing stones megalith alignment brittany france fog dramatic sunset mysterious ancient cinematic 8k detailed",
        "script": "En la región de Bretaña, en Francia, se extienden durante más de cuatro kilómetros las alineaciones de Carnac: casi tres mil piedras erectas dispuestas en filas perfectamente paralelas. Fueron colocadas hace más de seis mil años, antes que Stonehenge y las pirámides de Egipto. Algunas pesan hasta trescientas toneladas. Nadie sabe quiénes las pusieron ahí, ni por qué. Las leyendas locales dicen que son soldados romanos convertidos en piedra por el mago Merlín. Las teorías modernas apuntan a un enorme calendario astronómico o a una red de comunicación de energía. Las líneas de piedras están orientadas hacia puntos específicos del horizonte lunar. Lo más desconcertante es que las piedras fueron traídas de canteras a kilómetros de distancia, sin ninguna herramienta de metal. Carnac es el monumento megalítico más grande del mundo y uno de los más inexplicables."
    },
    {
        "title": "La Ciudad Sumergida de Yonaguni",
        "img_prompt": "yonaguni monument underwater ancient ruins japan submerged stone steps pyramid mysterious dramatic cinematic 8k detailed",
        "script": "En 1986, un instructor de buceo japonés descubrió frente a las costas de la isla de Yonaguni una estructura submarina que desafía cualquier explicación. A veintisiete metros de profundidad hay escalones perfectamente tallados, columnas verticales, plataformas horizontales y una enorme pirámide escalonada de veinticinco metros de altura. Algunos geólogos dicen que es un fenómeno natural causado por la erosión del agua. Pero otros señalan que los ángulos rectos, los escalones regulares y las columnas perfectas no pueden ser obra de la naturaleza. Si es artificial, fue construida hace al menos diez mil años, cuando el nivel del mar era más bajo. Esto significaría que existía una civilización avanzada en el Pacífico antes del fin de la última era glacial. La pirámide de Yonaguni podría ser la prueba de una historia que aún no conocemos."
    },
    {
        "title": "El Disco de Festos",
        "img_prompt": "phaistos disc ancient clay spiral symbols undeciphered mystery minoan crete dramatic cinematic close up dark 8k detailed",
        "script": "En 1908, arqueólogos que excavaban el palacio minoico de Festos, en la isla de Creta, encontraron un disco de arcilla de dieciséis centímetros de diámetro. Fue fabricado hace unos tres mil ochocientos años y está cubierto por ambas caras con símbolos en espiral que van del borde hacia el centro. Tiene doscientos cuarenta y uno símbolos agrupados en cuarenta y cinco signos distintos. Después de más de un siglo de intentos, ningún lingüista ni criptógrafo del mundo ha podido descifrarlo. No se parece a ningún sistema de escritura conocido. Puede leerse del centro hacia afuera o al revés. Algunos creen que es un himno religioso; otros, un mapa astronómico; otros, una lista de lugares. Solo se ha encontrado un objeto similar en el mundo. El Disco de Festos es el texto más antiguo del mundo que nadie puede leer."
    },
    {
        "title": "Göbekli Tepe y el Gran Diluvio",
        "img_prompt": "great flood ancient world catastrophe rising waters dramatic lightning storm cinematic dark apocalyptic 8k detailed",
        "script": "Muchas culturas del mundo antiguo, desde los sumerios hasta los aztecas, pasando por los griegos y los hebreos, comparten el mismo relato: en un tiempo remoto, un gran diluvio destruyó la civilización. Durante siglos se creyó que era solo un mito. Pero los geólogos han encontrado evidencias de un evento catastrófico real: hace unos doce mil años, el fin de la última glaciación provocó el deshielo masivo de los casquetes polares. El nivel del mar subió más de cien metros en pocos siglos, inundando grandes extensiones costeras donde vivían millones de personas. El Mar Negro era entonces un lago de agua dulce: en apenas décadas quedó conectado al Mediterráneo, anegando una superficie del tamaño de Francia. ¿Fue este el diluvio que todas las culturas recuerdan? La ciencia comienza a dar la razón a los mitos más antiguos de la humanidad."
    },
    {
        "title": "Los Annunaki: Los Dioses que Vinieron del Cielo",
        "img_prompt": "ancient sumerian gods annunaki alien beings descending from sky dramatic cosmic cinematic mysterious 8k detailed",
        "script": "Las tablillas de arcilla sumerias, escritas hace más de cinco mil años, describen unos seres llamados Annunaki que descendieron del cielo, enseñaron agricultura y escritura a los humanos, y los gobernaron como reyes. Los textos dicen que venían de un planeta llamado Nibiru. Durante siglos se leyeron como mitología. Pero el estudioso Zecharia Sitchin propuso en los años setenta una lectura literal: los Annunaki eran seres de otro mundo que modificaron genéticamente a los humanos para crear trabajadores. La ciencia convencional rechaza esta interpretación. Sin embargo, nadie explica satisfactoriamente por qué el Homo sapiens aparece de forma tan repentina en el registro fósil. Ni por qué los sumerios conocían la existencia de Urano y Neptuno, planetas que el mundo moderno no descubrió hasta el siglo diecinueve. Las tablillas sumerias siguen planteando preguntas que no tienen respuesta."
    },
    {
        "title": "El Misterio de los Olmecas",
        "img_prompt": "olmec colossal head ancient mexico stone sculpture jungle mysterious dramatic cinematic dark atmosphere 8k detailed",
        "script": "Los olmecas son la civilización más antigua de Mesoamérica, anterior a los mayas y aztecas. Florecieron en la costa del Golfo de México entre tres mil y dos mil años antes de Cristo. Dejaron atrás diecisiete cabezas colosales de basalto, algunas de hasta tres metros de altura y veinte toneladas de peso. Lo perturbador es que los rasgos faciales de estas cabezas parecen claramente africanos: labios gruesos, nariz ancha, pómulos prominentes. ¿Cómo llegaron personas con rasgos africanos a América dos mil años antes de Cristóbal Colón? Las piedras de basalto fueron transportadas desde canteras a cientos de kilómetros, cruzando pantanos y ríos sin animales de carga ni ruedas. Los olmecas inventaron el juego de pelota, el calendario y posiblemente la escritura mesoamericana. Y luego desaparecieron sin dejar rastro claro. Nadie sabe quiénes eran realmente."
    },
    {
        "title": "La Tumba Perdida de Alejandro Magno",
        "img_prompt": "alexander the great golden sarcophagus ancient egypt alexandria tomb mysterious dramatic cinematic dark 8k detailed",
        "script": "Alejandro Magno murió en Babilonia en el año trescientos veintitrés antes de Cristo, a los treinta y dos años. Conquistó el mayor imperio del mundo antiguo y cambió la historia de la civilización. Sin embargo, nadie sabe dónde está enterrado. Los textos históricos dicen que su cuerpo fue llevado primero a Menfis y luego a Alejandría, donde fue depositado en una tumba de cristal. El geógrafo Estrabón vio la tumba en el siglo primero antes de Cristo. Luego desapareció de los registros históricos. Han pasado más de dos mil años y ningún arqueólogo ha encontrado sus restos. Se han realizado más de ciento cuarenta expediciones buscando su tumba en Egipto. Algunos creen que está bajo la mezquita de Nebi Daniel en Alejandría. Otros que fue destruida en las revueltas del siglo cuarto. El conquistador más famoso de la historia permanece desaparecido."
    },
    {
        "title": "Los Frescos de Tassili y los Astronautas Antiguos",
        "img_prompt": "tassili cave paintings ancient astronaut helmet spacesuit sahara desert rock art mysterious cinematic dramatic 8k detailed",
        "script": "En el desierto del Sahara argelino, entre las rocas de la meseta de Tassili, hay más de quince mil pinturas rupestres con una antigüedad de cinco a diez mil años. Representan animales, escenas de caza, y figuras humanas normales. Pero también hay figuras completamente distintas: seres con enormes cabezas redondas, sin rasgos faciales reconocibles, con trajes que parecen escafandras. La teoría del arqueólogo Henri Lhote fue que representaban espíritus o dioses. Pero otros investigadores señalan el parecido extraordinario con los trajes modernos de astronautas. ¿Por qué artistas de hace ocho mil años pintarían figuras con cascos espaciales si no hubieran visto algo semejante? Los frescos de Tassili son parte del debate sobre los astronautas antiguos, una teoría que la ciencia rechaza pero que millones de personas en todo el mundo encuentran difícil de ignorar."
    },
    {
        "title": "El Santo Grial y los Caballeros Templarios",
        "img_prompt": "holy grail knights templar medieval castle dramatic torchlight mysterious ancient relic cinematic dark 8k detailed",
        "script": "Los Caballeros Templarios fueron la orden militar más poderosa de la Edad Media. Fundada en 1119 para proteger a los peregrinos en Tierra Santa, acumularon una riqueza y un poder que amenazaron a los reyes de Europa. En 1307, el rey Felipe IV de Francia ordenó su arresto masivo. La noche anterior a las detenciones, una flota de barcos templarios zarpó del puerto de La Rochela con un tesoro desconocido y nunca fue vista de nuevo. ¿Qué llevaban esos barcos? Los templarios habían excavado durante años bajo el Templo de Salomón en Jerusalén. Hay quien cree que encontraron el Santo Grial, el Arca de la Alianza o documentos que probarían verdades incómodas sobre el cristianismo. El tesoro templario nunca fue recuperado. Los documentos del proceso judicial del Papa Clemente siguen siendo los más secretos del Vaticano."
    },
    {
        "title": "Teotihuacán y el Mercurio Líquido",
        "img_prompt": "teotihuacan underground tunnel liquid mercury ancient pyramid mexico mysterious glowing dramatic cinematic dark 8k detailed",
        "script": "En 2015, el arqueólogo Sergio Gómez anunció un descubrimiento extraordinario bajo la Pirámide de la Serpiente Emplumada en Teotihuacán. Al explorar un túnel sellado hace dos mil años, encontró grandes cantidades de mercurio líquido esparcido por el suelo. ¿Por qué usaron mercurio los constructores de Teotihuacán? El mercurio era extremadamente difícil de obtener y transportar en el mundo antiguo. En la mitología, el mercurio se asocia con los inframundos y los viajes al más allá. Arqueólogos también han encontrado mercurio en tres tumbas reales mayas y en el complejo de Sipán en Perú. Algunos investigadores creen que el mercurio en movimiento creaba un efecto visual de lago o río brillante en las ceremonias subterráneas. Al fondo del túnel hay tres cámaras que aún no han sido excavadas completamente. Lo que guardan podría reescribir la historia de Mesoamérica."
    },
    {
        "title": "Los Nephilim: Los Gigantes de la Biblia",
        "img_prompt": "nephilim biblical giants ancient mysterious colossal beings dramatic dark sky cinematic fantasy realistic 8k detailed",
        "script": "El capítulo seis del Génesis contiene uno de los pasajes más enigmáticos de la Biblia: los Nephilim, hijos de los hijos de Dios y las hijas de los hombres, gigantes que existieron en la Tierra antes del Diluvio. El Libro de Enoc, un texto apócrifo de más de dos mil años, los describe como seres de cuatrocientos metros que enseñaron a los humanos metalurgia, astronomía y magia antes de ser destruidos por el Diluvio. Culturas de todo el mundo tienen leyendas de gigantes: los Gigantes de Grecia, los Titans, los Jotunn nórdicos, los Nephilim hebreos. ¿Son todos recuerdos del mismo evento? Se han encontrado esqueletos anómalos de gran tamaño en varios continentes, aunque su autenticidad es disputada. Si los Nephilim eran reales, serían la mayor anomalía en la historia de la evolución humana. El misterio sigue vivo en las páginas más antiguas del mundo."
    },
    {
        "title": "Los Dogon y el Secreto de la Estrella Sirio",
        "img_prompt": "sirius star night sky african tribe dogon ancient astronomical knowledge dramatic cinematic cosmic mysterious 8k detailed",
        "script": "Los Dogon son un pueblo de Mali, en África occidental, que vive en una región remota y aislada. En los años treinta, los antropólogos Marcel Griaule y Germaine Dieterlen descubrieron algo perturbador: los Dogon conocían la existencia de Sirio B, una estrella enana blanca invisible a simple vista que orbita alrededor de la brillante Sirio A. Los telescopios modernos no detectaron Sirio B hasta 1862, y la primera fotografía no se tomó hasta 1970. Los Dogon no solo sabían de su existencia, sino que conocían su período orbital de cincuenta años y el hecho de que era más densa que cualquier material conocido. Sus sacerdotes describían estas informaciones como conocimiento sagrado transmitido por seres que vinieron de esa estrella hace miles de años. ¿Cómo sabían los Dogon lo que la ciencia no descubrió hasta el siglo veinte? Nadie ha dado una respuesta satisfactoria."
    },
    {
        "title": "La Biblioteca de Alejandría: El Conocimiento Perdido",
        "img_prompt": "library of alexandria ancient egypt burning fire scrolls dramatic cinematic dark destruction knowledge loss 8k detailed",
        "script": "La Biblioteca de Alejandría fue el mayor repositorio de conocimiento del mundo antiguo. Fundada por Ptolomeo I en el siglo tercero antes de Cristo, llegó a contener entre cuatrocientos mil y setecientos mil rollos de papiro. Todo el saber acumulado por la humanidad hasta entonces: geometría, astronomía, medicina, filosofía, historia. Eratóstenes calculó allí la circunferencia de la Tierra con una precisión asombrosa. Aristarco propuso que la Tierra giraba alrededor del Sol, diecisiete siglos antes de Copérnico. ¿Qué más sabían? ¿Qué conocimientos se perdieron para siempre cuando la biblioteca fue destruida? No una sola vez: fue saqueada y quemada en varias ocasiones, por Julio César, por el edicto del emperador Teodosio, y finalmente por los árabes en el año 642. Con ella ardieron siglos de ciencia que la humanidad tardó mil años en redescubrir. El fuego que la destruyó aún nos hace daño."
    },
    {
        "title": "El Vimana: Las Naves Voladoras del Mundo Antiguo",
        "img_prompt": "ancient flying vehicle vimana vedic mythology sky dramatic cinematic golden craft mysterious clouds 8k detailed",
        "script": "Los textos sagrados del hinduismo, escritos hace más de tres mil años, describen con detalle unos vehículos voladores llamados Vimanas. El Ramayana narra batallas aéreas entre dioses en naves que se mueven a la velocidad del viento. El Mahabharata describe armas que destruyen ciudades enteras con un destello de luz y calor que hace que el agua hierva. Los textos sánscritos del Vaimanika Shastra detallan la construcción y pilotaje de diferentes tipos de naves voladoras. ¿Eran solo metáforas literarias o la descripción de tecnología real? En 1945, después de las bombas atómicas sobre Japón, Robert Oppenheimer citó el Mahabharata: ahora me he convertido en la muerte, el destructor de mundos. Creía que el texto antiguo describía explosiones nucleares. Si los Vimanas existieron, toda nuestra comprensión del desarrollo tecnológico de la humanidad es incorrecta."
    },
    {
        "title": "El Triángulo de las Bermudas",
        "img_prompt": "bermuda triangle ocean storm dark mysterious shipwreck plane disappearing dramatic cinematic fog 8k detailed",
        "script": "Entre las costas de Florida, las Bermudas y Puerto Rico existe una zona del océano Atlántico donde, según cientos de informes, barcos y aviones han desaparecido sin dejar rastro. El Triángulo de las Bermudas cobró fama en 1945 cuando el Vuelo 19, cinco aviones de la marina estadounidense en misión de entrenamiento, desapareció por completo. El avión de rescate enviado a buscarlos también desapareció. Trece personas se esfumaron en cielos despejados. Las explicaciones propuestas van desde bolsas de metano en el fondo marino que harían hundirse los barcos instantáneamente hasta tormentas electromagnéticas que inutilizan los instrumentos de navegación. Algunos investigadores apuntan a anomalías magnéticas severas en la zona. La realidad estadística es que el Triángulo no tiene más accidentes que otras rutas marítimas equivalentes. Pero los casos sin explicación siguen acumulándose, y nadie ha encontrado a las víctimas del Vuelo 19."
    },
    {
        "title": "Los Constructores de las Esferas de Costa Rica",
        "img_prompt": "costa rica stone spheres perfect ancient mysterious jungle archaeological site cinematic dramatic 8k detailed",
        "script": "En los años cuarenta, trabajadores que talaban la selva costarricense para cultivar plátanos comenzaron a encontrar esferas perfectas de piedra de todos los tamaños. Las hay del tamaño de una pelota de tenis y otras de más de dos metros de diámetro, con un peso de hasta dieciséis toneladas. Son de granodiorita, una piedra que no existe en la región y que debió transportarse desde las montañas. Su esferidad es casi perfecta: el margen de error es inferior al dos por ciento. Fueron creadas hace unos seiscientos a mil ochocientos años por una cultura precolombina que desapareció antes de la llegada de los españoles. No dejaron escritura. No sabemos cómo talaron una piedra tan dura con tal perfección sin herramientas de metal. No sabemos por qué las hacían. Las esferas de Costa Rica son la evidencia de una maestría artesanal que no debería existir."
    },
    {
        "title": "Sacsayhuamán: El Muro que Desafía la Física",
        "img_prompt": "sacsayhuaman inca stone walls cusco peru massive polygonal blocks dramatic stormy sky cinematic mysterious 8k detailed",
        "script": "Sobre la ciudad de Cusco, en Perú, se alzan las murallas de Sacsayhuamán, construidas por los incas hace unos quinientos años. Sus bloques de piedra son los más grandes utilizados en cualquier construcción del mundo precolombino: algunos pesan más de trescientas toneladas. Están cortados con tal precisión que encajan perfectamente entre sí formando superficies poligonales complejas de hasta doce ángulos. Ni el papel más fino puede introducirse entre ellos. No hay cemento, no hay argamasa. Un terremoto en 1950 destruyó gran parte de Cusco colonial pero las murallas incas permanecieron intactas. Los ingenieros modernos no saben cómo transportaron esas piedras desde canteras a treinta kilómetros de distancia, cómo las elevaron hasta la colina y cómo las cortaron con esa precisión. Los españoles, cuando llegaron, creyeron que solo los demonios podían haber construido semejante obra."
    },
]
